const KEY = ['QUIZ'];

const CATEGORY_KEY = [...KEY, 'CATEGORY'];
const ANSWER_KEY = [...KEY, 'ANSWER'];
const ANSWER_DETAIL_KEY = [...KEY, 'ANSWER', 'DETAIL'];
const ANOTHER_ANSWER_KEY = [...KEY, 'ANSWER', 'ANOTHER'];

export { KEY, CATEGORY_KEY, ANSWER_KEY, ANOTHER_ANSWER_KEY, ANSWER_DETAIL_KEY };
